server:
  port: 9000


spring:
  datasource:
    url: jdbc:mysql://39.99.154.145:3306/hello?serverTimezone=GMT%2B8
    username: root
    password: Mysql-xw36736634
    driverClassName: com.mysql.cj.jdbc.Driver

