mybatis:
  type-aliases-package: com.ahhtou.pojo
  mapper-locations: classpath:mapper/*.xml



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: 123
    driverClassName: com.mysql.cj.jdbc.Driver