spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/hello?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
